Issue #2819970 added a new field formatter
purushotamrai/addtocalender pull request #6
Opened 2017-10-10 11:51 UTC by guptahemant

2017-10-10 12:15 UTC, purushotamrai requested changes

2017-10-10 12:15 UTC, purushotamrai commented on addtocalendar.module
> +  // dsm(get_class_methods($plugin));
Remove dsm lines

2017-10-10 12:15 UTC, purushotamrai commented on addtocalendar.module
> +    //make sure to avoid confliction in case add_to_calendar field formatter is used
Coding Standard 
// Make sure to avoid confliction in case add_to_calendar field formatter is used.

2017-10-10 12:15 UTC, purushotamrai commented on addtocalendar.module
> +  if($plugin->getPluginId() !== 'add_to_calendar'){
space after if
I would recommend to install phpsniffer on your local

2017-10-10 13:23 UTC, purushotamrai requested changes

2017-10-10 13:23 UTC, purushotamrai commented on src/Plugin/Field/FieldFormatter/AddToCalendar.php
> +    dsm($settings);
Remove this also.

2017-10-10 13:23 UTC, purushotamrai commented on src/Plugin/Field/FieldFormatter/AddToCalendar.php
> +      'addtocalendar_show' => '1',
Show Option should not be in Field Formatter

2017-10-10 13:23 UTC, purushotamrai commented on src/Plugin/Field/FieldFormatter/AddToCalendar.php
> +class AddToCalendar extends DateTimeDefaultFormatter {
Make class name AddToCalendarFormatter

2017-10-10 13:23 UTC, purushotamrai commented on src/Plugin/Field/FieldFormatter/AddToCalendar.php
> +class AddToCalendar extends DateTimeDefaultFormatter {
Just an recommendation, check drupal core/contrib for reference.

2017-10-10 13:23 UTC, purushotamrai commented on src/Plugin/Field/FieldFormatter/AddToCalendar.php
> +class AddToCalendar extends DateTimeDefaultFormatter {
It may be possible I'm wrong here.

2017-10-10 13:23 UTC, purushotamrai commented on addtocalendar.module
>  function addtocalendar_field_formatter_third_party_settings_form($plugin, $field_definition, $view_mode, $form, $form_state) {
Need to remove .DS_Store file

2017-10-10 13:23 UTC, purushotamrai commented on src/Plugin/Field/FieldFormatter/AddToCalendar.php
> +    $form += _addtocalendar_build_form($settings, $field_definition);
As discussed, this won't work with views.

2017-10-16 18:39 UTC, purushotamrai approved these changes
Rest Looks good to me, for initial start

2017-10-16 18:39 UTC, purushotamrai commented on src/Plugin/Field/FieldType/AddToCalendarField.php
> +      'on_label' => new TranslatableMarkup('Add to Calendar'),
we can use $this->t()

2017-10-16 18:39 UTC, merged

2017-10-17 03:53 UTC, guptahemant commented on src/Plugin/Field/FieldType/AddToCalendarField.php
> +      'on_label' => new TranslatableMarkup('Add to Calendar'),
Thanks